export const arrMessages = [
  {
    id_message:2003,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
  {
    id_message:2004,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
  {
    id_message:2005,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
  {
    id_message:2006,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
  {
    id_message:2007,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
  {
    id_message:2008,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
  {
    id_message:2008,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
  {
    id_message:2008,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
  {
    id_message:2008,
    id_dialog:1,
    id_sender:1,
    content:"for roma from alex",
    message_time:"2022-11-27",
    isRead:false,
    isDeleted:false,
  },
];